[package]
name = "backtest-example"
version = "0.1.0"
edition = "2024"
description = "Solana simulation examples"

[dependencies]
anyhow = "1"
base64 = "0.22"
bincode = "1"
clap = { version = "4", features = ["derive", "env"] }
reqwest = { version = "0.12", features = ["json"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
serde_json = "1"
futures = "0.3"
serde = { version = "1", features = ["derive"] }
simulator-api = { git = "https://github.com/nitro-svm/nitro-stream", rev = "b7e9480e23deb3ce1145dfa61b30cf139a640a12" }
simulator-client = { git = "https://github.com/nitro-svm/nitro-stream", rev = "b7e9480e23deb3ce1145dfa61b30cf139a640a12" }
solana-account-decoder = "4.1.0"
solana-address = "2.6.0"
solana-client = "4.1.0"
solana-commitment-config = "3.1.1"
solana-loader-v3-interface = "7.0.0"
solana-pubkey = "3"
solana-rpc-client-api = "4.1.0"
solana-signature = "3.1.0"
solana-message = "4.1.1"
solana-transaction = "4.1.1"
solana-transaction-error = "3.2.0"
solana-transaction-status = "4.1.0"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2"
